### ISSUE TITLE
lab.md

### ISSUE THREAD

**Issue by HienThuThiDai** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure.fr-fr#1]
English:
Configure Start Menu & Taskbar to only include the following icons:

Current Translation:
Configurez le menu Démarrer et la Barre des tâches pour inclure uniquement les icônes suivantes :

Suggested Translation:
Configurez le menu Démarrer et la barre des tâches pour inclure uniquement les icônes suivantes :

Description:
Capitalization issue: Please follow French capitalization rules

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by olprod** [comment]
![image](https://user-images.githubusercontent.com/16075726/180705662-413c27de-8f40-4d34-9d7a-44278f426c60.png)
