### ISSUE TITLE
All files

### ISSUE THREAD

**Issue by HienThuThiDai** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure.fr-fr#79]
Images strings should be localized

77 files in the AZ-204-DevelopingSolutionsforMicrosoftAzure.fr-fr-OLPRODLOC  02_Target\AZ-204-DevelopingSolutionsforMicrosoftAzure.fr-fr-OLPRODLOC\Instructions\Labs\media folder from 10_create_sb_namespace.png until Lab12-Diagram.png (77 files)

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by stonezy123** [comment]
The image locfile show blocked status, I re-set prehandoff status, waiting for check in to locrepo. [ICMS QUERY](https://wus-000.icms.osi.office.net/vantagepoint/QueryPanel.aspx?Tenant=C%26E&Query=PFZQUT48TEZPPkZhbHNlPC9MRk8%2bPElEPkZhbHNlPC9JRD48RUxDPkZhbHNlPC9FTEM%2bPEFNUD5GYWxzZTwvQU1QPjxTT0hSSVI%2bRmFsc2U8L1NPSFJJUj48U0hSUD5GYWxzZTwvU0hSUD48U0FUTz5GYWxzZTwvU0FUTz48U0FMTz5UcnVlPC9TQUxPPjxRRT4%2bMjwvUUU%2bPFFUPj48UVIgSWQ9IjEiIENQSUQ9IjAiPkN1cnJlbnQ7RmlsZXM7SG9zdCBDb250ZW50IFN0b3JlO0VxdWFsO0xBQl9BWi0yMDQ8L1FSPjxRUiBJZD0iMiIgQ1BJRD0iMCI%2bYW5kO0N1cnJlbnQ7TG9jRmlsZXM7TGFuZ3VhZ2U7RXF1YWw7RnJlbmNoPC9RUj48UVIgSWQ9IjQiIENQSUQ9IjAiPmFuZDtDdXJyZW50O0ZpbGVzO0hvc3QgRmlsZSBSZWZlcmVuY2U7Q29udGFpbnM7SW5zdHJ1Y3Rpb25zL0xhYnMvbWVkaWEvPC9RUj48L1FUPjxSRz48R0M%2bTlVMTDwvR0M%2bPC9SRz48L1ZQUT4%3d)
