### ISSUE TITLE
Various Labs: Minor issues – extra spaces, missing periods, upper case consistency

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure.fr-fr#81]
A recent QA of this series noted multiple issues in the Instructions that can be considered 'cosmetic':  They do not lead to blocking in completion of the labs, however I wanted to call them out so that if the CO wishes to do a pass through the markdown at a future date to correct them they will be aware and have some references.  The screenshots below are not specifically from this course, but meant to be an example of this minor issue.

**<ins>Extra space:</ins>**   
 
![image](https://user-images.githubusercontent.com/49700217/198408017-9d934fbc-dfbf-4ec9-a7b0-219f495363b8.png)

    Seen in Labs: 4, 9, 12

**<ins>Missing full stop (period):</ins>**
 
![image](https://user-images.githubusercontent.com/49700217/198408048-7d5e0012-f42c-4f36-8744-0c618dd46619.png)

    Seen in Labs: 1, 2, 6-8, 11, 12

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by chriscarty00** [comment]
https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure.fr-fr/blob/master/Instructions/Labs/AZ-204_lab_01.md

https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure.fr-fr/blob/master/Instructions/Labs/AZ-204_lab_02.md
