### ISSUE TITLE
Module 5 FR does not match English Mod 5 Recent Updates.

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure.fr-fr#83]
Do we have a timeline for when Module 5 here (and in any other localized languages) will be updated to match the updates made to the ENG version of the course ~2 weeks ago?

**Comment by chriscarty00** [comment]
need to refer to PM 
Locfile [https://wus-000.icms.osi.office.net/vantagepoint/QueryPanel.aspx?Tenant=CAICritical&Query=PFZQUT48TEZPPkZhbHNlPC9MRk8%2bPElEPkZhbHNlPC9JRD48RUxDPkZhbHNlPC9FTEM%2bPEFNUD5GYWxzZTwvQU1QPjxTT0hSSVI%2bRmFsc2U8L1NPSFJJUj48U0hSUD5UcnVlPC9TSFJQPjxTQVRPPkZhbHNlPC9TQVRPPjxTQUxPPlRydWU8L1NBTE8%2bPFFFPj4yPC9RRT48UVQ%2bPjxRUiBJZD0iMSIgQ1BJRD0iMCI%2bQ3VycmVudDtGaWxlcztIb3N0IENvbnRlbnQgU3RvcmU7RXF1YWw7V1dMPC9RUj48UVIgSWQ9IjIiIENQSUQ9IjAiPmFuZDtDdXJyZW50O0ZpbGVzO0hvc3QgQXNzZXQgSUQ7RXF1YWw7QVotMjA0X2xhYl8wNy5tZDwvUVI%2bPFFSIElkPSI1IiBDUElEPSIwIj5hbmQ7Q3VycmVudDtMb2NGaWxlcztMYW5ndWFnZTtFcXVhbDtKYXBhbmVzZSAoSmFwYW4pPC9RUj48L1FUPjxSRz48R0M%2bTlVMTDwvR0M%2bPC9SRz48L1ZQUT4%3d](url)

**Comment by stonezy123** [comment]
Updated. https://github.com/MicrosoftLearning/AZ-204-DevelopingSolutionsforMicrosoftAzure.fr-fr/blob/OLPRODLOC/Instructions/Labs/AZ-204_lab_05.md
